#!/usr/bin/env bash
#Transfer file from client to a serveri

path_to_file="$1"
username="$2"
ip="$3"
path_to_ssh_key="$4"

# Check if the required number of parameters is passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$ip":/home/"$username"/
fi

