#!/bin/bash
# Update package list and install Nginx

sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx --allow-downgrade

# Configure Nginx to listen on port 80
sudo sed -i 's/.*listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create an index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null


