#!/usr/bin/env bash
#The script prints "Best School" 10 times and @4 t prints badd luck and @8 it prints good luck
counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "Bad luck"
    elif [ $counter -eq 8 ]; then
        echo "Good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done

