#!/usr/bin/env bash
#Bad lucks using case

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo -e "$counter\nbad luck from China"
            ;;
        9)
            echo -e "$counter\nbad luck from Japan"
            ;;
        17)
            echo -e "$counter\nbad luck from Italy"
            ;;
        *)
            echo -e $counter
            ;;
    esac

    ((counter++))
done

